## BACKPROPAGATION AND FEEDFORWARD OF NEURAL NETWORKS

### SIMPLE NEURAL NETWORK METHOD

In [2]:
import numpy as np

In [3]:
# x = no. of hours sleeping, no. of hours studing) , y = test score of the student on x 
X = np.array(([2,9],[1,5],[3,6]), dtype = float)
y = np.array(([92],[86],[89]), dtype = float) 

# scale units
X = X/np.max(X,axis=0) # maximum of x array
y = y/100  # maximum of test score is 100

print(X)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [4]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputsize = 2
        self.outputsize = 1
        self.hiddensize = 3
        
        # heights 
        self.w1 = np.random.randn(self.inputsize, self.hiddensize) # (3*2) wiights from input layer to hidden layer
        self.w2 = np.random.randn(self.hiddensize, self.outputsize) # (3*1) weights from hidden layer to output layer
        
    def forwardfeed(self, X): 
        self.z = np.dot(X,self.w1) # the product of inputs x and the first set of weights(3*2) 
        self.z2 = self.sigmoid(self.z) # its activation function where normalize the variable 0 to 1
        self.z3 = np.dot(self.z2, self.w2) # the product of hidden layer (z2) and second set of weights(3*1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv = False): # sigmoid derivative is function used in backpropagation to find the tangent
        if  ( deriv == True):           # of the slope. so where actually minimize the cost or loss of function by finding 
            return s * (1 - s)          # the optimal set of  model parameters. 
        return 1/ (1 + np.exp(-s))      # if its forwardfeed where sigmoid deriv has to turn off
    
    def backpropagate(self, X, y, output):
        self.output_error = y - output # error in output
        self.output_delta = self.output_error * self.sigmoid(output, deriv=True) # applying sigmoid derivative to output error
        
        self.z2_error = self.output_delta.dot(self.w2.T) #z2 error: how much our hidden layer weigts contributes to output error 
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv= True)# applying sigmoid derivative to z2 error
        
        self.w1 += X.T.dot(self.z2_delta)  # its high time to update our weights in input to hidden layer
        self.w2 += self.z2.T.dot(self.output_delta)# updating weights in hidden layer to output layer

    def train(self, X, y):
        output = self.forwardfeed(X) 
        self.backpropagate(X, y, output) 
        
NN = NeuralNetwork()

for i in range(1000): # no. of times to train
    NN.train(X, y) 

print("input:", (X))
print("actual output:", (y))
print("loss: ", (np.mean(np.square(y - NN.forwardfeed(X)))))
print("\n")
print("predicted output: ", (NN.forwardfeed(X)))
    
        

input: [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output: [[0.92]
 [0.86]
 [0.89]]
loss:  0.00012465496234554196


predicted output:  [[0.91071503]
 [0.8544489 ]
 [0.90602933]]


### Alternative method

### Training process

In [5]:
import numpy as np

# sigmoid function to normalize inputs
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# sigmoid derivatives to adjust synaptic weights
def sigmoid_derivative(x):
    return x * (1 - x)

# input dataset
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

# output dataset
training_outputs = np.array([[0,1,1,0]]).T

# seed random numbers to make calculation
np.random.seed(1)

# initialize weights randomly with mean 0 to create weight matrix, synaptic weights
synaptic_weights = 2 * np.random.random((3,1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

# Iterate 10,000 times
for iteration in range(10000):

    # Define input layer
    input_layer = training_inputs
    # Normalize the product of the input layer with the synaptic weights
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

    # how much did we miss?
    error = training_outputs - outputs

    # multiply how much we missed by the
    # slope of the sigmoid at the values in outputs
    adjustments = error * sigmoid_derivative(outputs)

    # update weights
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training: ')
print(synaptic_weights)

print("Output After Training:")
print(outputs)


Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Output After Training:
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]


### complete process

In [6]:
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        # Seed the random number generator
        np.random.seed(1)

        # Set synaptic weights to a 3x1 matrix,
        # with values from -1 to 1 and mean 0
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1

    def sigmoid(self, x):
        """
        Takes in weighted sum of the inputs and normalizes
        them through between 0 and 1 through a sigmoid function
        """
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        """
        The derivative of the sigmoid function used to
        calculate necessary weight adjustments
        """
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        """
        We train the model through trial and error, adjusting the
        synaptic weights each time to get a better result
        """
        for iteration in range(training_iterations):
            # Pass training set through the neural network
            output = self.think(training_inputs)

            # Calculate the error rate
            error = training_outputs - output

            # Multiply error by input and gradient of the sigmoid function
            # Less confident weights are adjusted more through the nature of the function
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))

            # Adjust synaptic weights
            self.synaptic_weights += adjustments

    def think(self, inputs):
        """
        Pass inputs through the neural network to get output
        """
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


if __name__ == "__main__":

    # Initialize the single neuron neural network
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    # The training set, with 4 examples consisting of 3
    # input values and 1 output value
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T

    # Train the neural network
    neural_network.train(training_inputs, training_outputs, 10000)

    print("Synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    A = str(input("Input 1: "))
    B = str(input("Input 2: "))
    C = str(input("Input 3: "))
    
    print("New situation: input data = ", A, B, C)
    print("Output data: ")
    print(neural_network.think(np.array([A, B, C])))


Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Input 1: 1
Input 2: 0
Input 3: 0
New situation: input data =  1 0 0
Output data: 
[0.99993704]
