In [1]:
import numpy as np

In [2]:
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [4]:
filter = an_array>15
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [5]:
print(an_array[filter])

[21 22 31 32]


In [6]:
an_array[(an_array % 2 ==0)]

array([12, 22, 32])

In [7]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [8]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [14]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)



Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [15]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])


Values in the array at those indices:  [11 22 33 41]


In [16]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)



Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [23]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)
unsorted.reshape(2,5)

[-0.20351506  0.71010277  0.46681006 -1.25736023 -0.61867488 -0.49524531
  1.52372088 -1.00401459 -0.01773758  0.83357435]


array([[-0.20351506,  0.71010277,  0.46681006, -1.25736023, -0.61867488],
       [-0.49524531,  1.52372088, -1.00401459, -0.01773758,  0.83357435]])

In [3]:
import numpy as np
x=np.random.randn(10)
print(x)

[ 0.39538257 -0.10318383  0.73013115 -0.09805453 -0.12206035  0.21104405
 -0.63441045 -0.01477125  1.02846859 -1.38333384]


In [5]:
y=np.array(x)
print(y)

[ 0.39538257 -0.10318383  0.73013115 -0.09805453 -0.12206035  0.21104405
 -0.63441045 -0.01477125  1.02846859 -1.38333384]


In [10]:
y.sort()
print(y)

[-1.38333384 -0.63441045 -0.12206035 -0.10318383 -0.09805453 -0.01477125
  0.21104405  0.39538257  0.73013115  1.02846859]


In [12]:
x.sort()
print(x)

[-1.38333384 -0.63441045 -0.12206035 -0.10318383 -0.09805453 -0.01477125
  0.21104405  0.39538257  0.73013115  1.02846859]


In [13]:
import numpy as np
start = np.zeros((4,3))
x=np.array([[0,1,3,4]])
x= x.T
y=start + x
print(y)


[[0. 0. 0.]
 [1. 1. 1.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [16]:
x = np.array([ 23.23, 24.24] )
np.save("an_array",x)
np.load("an_array.npy")

array([23.23, 24.24])

In [17]:
# Python Program illustrating 
# dot product of two vectors 

# Importing numpy module 
import numpy as np 

# Taking two 1D array 
a = 3 + 1j
b = 7 + 6j

# Calculating dot product using dot() 
print(np.dot(a, b)) 



(15+25j)


In [9]:
import numpy as np
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, True, True, False, True])

In [10]:
print(filter)

[ True  True  True False  True]


In [11]:
out = np.where(filter, x_1, y_1)
print(out)


[ 1  2  3 44  5]


In [5]:
mat = np.random.rand(5,5)
mat


array([[0.98540079, 0.69756387, 0.03229178, 0.58657289, 0.0116987 ],
       [0.70613465, 0.09981679, 0.41871018, 0.55276822, 0.0870796 ],
       [0.71905616, 0.21463132, 0.41272296, 0.61051417, 0.1570002 ],
       [0.42962373, 0.07704264, 0.30787838, 0.50813913, 0.34962235],
       [0.40570269, 0.96551524, 0.91707122, 0.48814781, 0.22392606]])

In [7]:
np.where( mat > 0.5, 1000, -1)

array([[1000, 1000,   -1, 1000,   -1],
       [1000,   -1,   -1, 1000,   -1],
       [1000,   -1,   -1, 1000,   -1],
       [  -1,   -1,   -1, 1000,   -1],
       [  -1, 1000, 1000,   -1,   -1]])

In [2]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [3]:
a_slice = an_array[1:3]
print(a_slice)


[[21 22 23 24]
 [31 32 33 34]]


In [5]:
print("Before:", an_array[1, 0])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[1, 0])


Before: 21
After: 1000


In [6]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000


In [7]:
x = arange(size)
print( type(x) )


<class 'numpy.ndarray'>


In [14]:
# here we pass nd_array.sum()
timer_npy = Timer("x.sum()", "from __main__ import x")

print("Time taken by numpy x: %f seconds" % 
      (timer_npy.timeit(timeits)/timeits))


Time taken by numpy x: 0.001434 seconds


In [2]:
y=list(range(size))

In [3]:
timer_list=Timer("sum(y)","from __main__ import y")
print("time taken by list y: %f seconds" % (timer_list.timeit(timeits)/timeits))

time taken by list y: 0.077089 seconds


In [5]:
import numpy as np

In [6]:
arr_bools = np.array([ True, False, True, True, False ])


In [10]:
arr_bools.any()


True

In [14]:
arr_bools.all()


False

In [30]:
Y = np.random.normal(size = (1,7))[0]
print(Y)


[ 0.15394734 -0.27925222  0.56102788  0.71415999  0.50743129  1.31450952
  1.78272739]


In [33]:
z=np.random.randint(low=1,high=5,size=4)
print(z)

[2 2 3 1]


In [34]:
np.random.permutation(z)

array([3, 2, 1, 2])

In [37]:
np.random.uniform(size=4)

array([0.92703959, 0.46446054, 0.72813243, 0.82203796])

In [48]:
np.random.normal(size=(1,6))[0]

array([-0.30781173, -0.45685631,  1.37726944,  0.70273011, -1.07782962,
        1.66946767])

In [49]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)


[[ 8  7]
 [22 21]]

[[19  4]
 [ 7 25]]


In [52]:
np.vstack((K,M))


array([[ 8,  7],
       [22, 21],
       [19,  4],
       [ 7, 25]])

In [53]:
np.hstack((K,M))

array([[ 8,  7, 19,  4],
       [22, 21,  7, 25]])

In [55]:
np.concatenate([K,M],axis=0)

array([[ 8,  7],
       [22, 21],
       [19,  4],
       [ 7, 25]])

In [57]:
np.concatenate([K,M.T],axis=1)

array([[ 8,  7, 19,  7],
       [22, 21,  4, 25]])